### ISSUE TITLE
"404 not found" on attack-less requests and extra slashes

### ISSUE THREAD

**Issue by viskey98** [mushorg/snare#101]
@rnehra01 mentioned in the issue #66 that if we do a request like : 
"www.example.com/path?foo=bar "
snare returns a  "404 not found error" even though there is no attack present in the foo parameter. 
This should not be the case as the actual website returns the "www.example.com/path" web-page  instead of a 404 error. I think this part should be considered as a separate bug as the working of the honeypot is itself not as expected compared to the working of the actual website , which can compromise our honeypot to the attackers.

**Comment by viskey98** [comment]
Iam myself working on the same :)

**Comment by viskey98** [comment]
Today while running snare , I realized even a http request like "http://www.example.com/index.html/" will result in "404 not found" whereas we expect it to show up the web-page like: "http://www.example.com/index.html" , which all the websites do.

**Comment by viskey98** [comment]
Iam working on this issue myself :)

**Comment by afeena** [comment]
Great, thanks for reporting this problem :)
