### ISSUE TITLE
Difficulty in navigating through documentation for people who are new to snare's git repo

### ISSUE THREAD

**Issue by viskey98** [mushorg/snare#104]
I think it will be nice to have a Index.md file in the "/docs" folder, which will contain the hyperlinks of the documentation files to navigate directly into the desired content , instead of searching for the file name in the "/docs/source" folder manually ( which can become difficult in case of too many docs in the future).
And we can reference this (Index.md) file in our README.md file , so that someone who is new and reads the read-me can navigate into the docs without any difficulty.
This difficulty was experienced by a person in my institution , and i would like to fix it :)

**Comment by viskey98** [comment]
For info : A pr fixing the same issue is also done on TANNER'S side.

**Comment by afeena** [comment]
In my opinion, README.md is enough for github repo. Documentation should be built locally or better move to readthedocs.org #74 

But it is only my opinion :) I will be glad to get another ones

**Comment by viskey98** [comment]
I created this issue because one of my friend (beginner to python and cyber security) in my institution found difficulty in finding the documentation, He said : when he clicked the link in readme.md `See the docs for more info` , he was redirected to the index.rst  and he could only find the names of the doc files , and then he didn't know how to proceed. So i felt it might be useful to create such issue , else if its not necessary , Iam okay with anything :)

**Comment by viskey98** [comment]
@afeena have we moved the docs to readthedocs.org yet?

**Comment by VineethReddy02** [comment]
Hello Everyone!!
 My name is Vineeth, I would like to work on improvement of existing tool for SNARE/ TANNER for GSOC 2018 this summer. Can you guide how can i start with this project.

Thank you!

**Comment by afeena** [comment]
Hi @VineethReddy02,

First of all, you can join our slack :) You can find information about slack on the webpage https://honeynet.org/gsoc2018/ideas
Then look at the code, play around with software and go through the issues.

Do not hesitate to ask questions :)

**Comment by glaslos** [comment]
@viskey98 what is your opinion on #74 ?

**Comment by viskey98** [comment]
@glaslos  I feel moving the docs to readthedocs.org will make the presentation of the docs a lot better . Navigation can then be also made easier by modifying the hyperlink in the README.md , stating "See the docs for more info" to the URL of the snare's doc in the readthedocs.org website. :)

**Comment by glaslos** [comment]
http://snare.readthedocs.io/en/latest/
