### ISSUE TITLE
Test the clonging utility against a vanilla wordpress instance

### ISSUE THREAD

**Issue by glaslos** [mushorg/snare#11]
Setup a Wordpress instance or use a demo (check the template store on wordpress.com)
Run the clone utility: https://github.com/mushorg/snare/blob/master/clone.py
Make sure the page renders correctly (JS, images, CSS).
Moved from here: https://github.com/mushorg/tanner/issues/15

**Comment by afeena** [comment]
I tested with my own wordpress site.

This is the original site:

<img width="340" alt="ya1twsc 1" src="https://cloud.githubusercontent.com/assets/8390928/15610985/9d39267e-2441-11e6-8a54-c5fe79b3eba9.png">

This is cloned  site:
<img width="340" alt="ya1twsc 1" src="http://i.imgur.com/JyzqaIe.png">

**Comment by glaslos** [comment]
LGTM
