### ISSUE TITLE
Bad file extensions

### ISSUE THREAD

**Issue by xandfury** [mushorg/snare#116]
It is convention to not use `.py` extension for python scripts. [`clone`](https://github.com/mushorg/snare/blob/master/clone.py) and [`snare`](https://github.com/mushorg/snare/blob/master/snare.py) python scripts have `.py` extensions. Please change these. Use .py for only python libraries

More info [here](https://stackoverflow.com/questions/49472256/is-it-bad-practice-to-use-py-extension-for-python-executables?noredirect=1#comment85947148_49472256)

**Comment by viskey98** [comment]
@xandfury we have planned on reconstructing snare and cloner code base to improve its architecture in this summer, that time this issue will be solved automatically.

**Comment by viskey98** [comment]
This issue was fixed after the new release of `snare v0.3`
