### ISSUE TITLE
Detect malicious website

### ISSUE THREAD

**Issue by mzfr** [mushorg/snare#118]
It would be a nice thing if cloner can check for malicious content within the website before cloning it and  maybe produce a warning for it.
The process for cloning would be something like:
* `sudo python3 clone.py --target http://example.com`
* If website have malicious content generate a warning 
   `website may contain malicious content are you sure you want to clone the website ?`
* If yes then clone the website else abort the process 

I think implementing this from the scratch could be a bit of tedious task so for starter we can use [Google safe browsing API](https://developers.google.com/safe-browsing/v4/) or some other websites like [URLvoid](http://www.urlvoid.com/)

@afeena what do you think about it ?

**Comment by viskey98** [comment]
@mzfr This seems to be a good idea, but its difficult to guess if a whole website is malicious or not with just its index-page URL. And the 3rd party API's u have mentioned check maliciousness for URLs. So we need to check it for every url of the website. This can even slow down our cloning process. What do you think about this?

**Comment by mzfr** [comment]
@viskey98 managing the process speed won't be a problem since google safe browsing accept 500 URLs in single post request.

But we can leave this issue for right now because @glaslos told me that at this point this isn't a very important feature.

**Comment by viskey98** [comment]
@mzfr Google safe browsing website itself states a disadvantage like:
`Response time: Every lookup request is processed by the server. We don't provide guarantees on lookup response time.`
So if we implement this for every URLs (of the to-be-cloned website) it can be costly for certain websites that's what i meant.
And yah like you said, I guess this issue can be looked up later.

**Comment by glaslos** [comment]
IIRC Google Safe Browsing is not live scanning the web page but gives you a historic verdict. So you do it once per domain.
