### ISSUE TITLE
not able to run snare 

### ISSUE THREAD

**Issue by anjali-shukla** [mushorg/snare#119]
I have created a simple login form and hosted it on a local machine .I was able to clone the web page but when I run snare it gives error.The screen shot of error is attached below.
![snare](https://user-images.githubusercontent.com/35517694/38161900-e93ca9a4-34f4-11e8-9a37-bfe3ec561890.png)

**Comment by afeena** [comment]
Hi. How you clone your page? Could you please show exact command?

**Comment by anjali-shukla** [comment]
sudo python3 clone.py --target http://10.114.56.197/pra1.html

**Comment by afeena** [comment]
I can make a guess, that you have only one page in your meta.json. You can check it and try try to run snare with ```--index-page 
pra1.html ```

**Comment by anjali-shukla** [comment]
yeah , it worked .
Thank you so much .
