### ISSUE TITLE
snare is giving error

### ISSUE THREAD

**Issue by anjali-shukla** [mushorg/snare#121]
i changed aiohttp version in tanner to 0.14.0, after that snare started giving error .
![error](https://user-images.githubusercontent.com/35517694/38190583-8c1216ee-3682-11e8-966f-e1f0bb6e5974.png)

**Comment by viskey98** [comment]
go into snare's folder and please run: `pip3 install -r requirements.txt`
If you do this, you will install the dependencies (with required version) for snare and will fix this issue.
After this every time before you run tanner, make sure docker is running. If not start docker using this command : `sudo service docker start` 
Docker will create a virtualisation for the dependencies (with required version) required for tanner.
I hope this helps :)

**Comment by anjali-shukla** [comment]
Docker is running and i have installed all the requirements.

**Comment by viskey98** [comment]
I meant if you installed the tanner's requirements as the latest, the machine will have tanner's dependency versions. So you please install snare's side dependencies again and then try.
If it still doesn't work, try a fresh instance of snare, it reset ur files using git.
Because it seems to work fine in my machine :)

**Comment by afeena** [comment]
@anjali-shukla it seems like the problem with tanner. (I guess tanner response something like 500 error). Please check your tanner first (check you tanner error log at /opt/tanner/tanner.err)

**Comment by afeena** [comment]
@anjali-shukla has the problem been resolved?

**Comment by t3chn0m4g3** [comment]
Try running with `--no-dorks`

**Comment by glaslos** [comment]
Assuming the issue has been resolved.
