### ISSUE TITLE
Webpage Inaccessible from Remote Machine

### ISSUE THREAD

**Issue by Siegmy3r** [mushorg/snare#122]
Hello, I am trying to use Snare on my network at home and I am hosting it on a Raspberry Pi. I have gotten Snare to run and a page to display, but the page can only be seen from the Raspberry Pi itself, not any remote machine. 

I cannot display the page by port forwarding through my router or by using a LAN connection. I checked to see if there was a firewall on my router that would block the traffic, but there was none. To eliminate the variable of the router, disconnected both my laptop and my Raspberry Pi from the router entirely and directly connected them together via Ethernet cable. Still, a connection to port 80 from my laptop was refused and a connection to the localhost on the Pi was allowed. 

I checked the documentation on Raspberry Pis and found no record of a firewall that could have been installed by default and I did not install a firewall. To be extra sure, I checked all services on the Pi to make sure there were no firewalls and found nothing. I also checked to see if there was anything that was running on port 80 that could be interfering with Snare and there was nothing. Could Snare be the issue?

Perhaps I have misunderstood the purpose of this project, but I assume that honeypots are meant to be accessed by remote machines. I am not sure what I have done wrong.

Thank you for your help,
Siegmy3r

**Comment by Siegmy3r** [comment]
Fixed my own problem! It runs on localhost by default. You have to specify the IP address of the machine you are on so that it can be accessed by other machines.

**Comment by viskey98** [comment]
@afeena as this issue is fixed, we should close this issue :)
