### ISSUE TITLE
Error runinng clone.py

### ISSUE THREAD

**Issue by deanhinson** [mushorg/snare#124]
wheh i run:

sudo python3 clone.py --target http://***url**.com

i get the error:
Traceback (most recent call last):
  File "clone.py", line 25, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'

pip3 freeze
aiohttp==3.2.1
async-timeout==3.0.0
attrs==18.1.0
automationhat==0.1.0
beautifulsoup4==4.6.0
blinker==1.3
blinkt==0.1.1
buttonshim==0.0.2
Cap1xxx==0.1.3
chardet==3.0.4
click==6.6
colorama==0.3.7
cryptography==1.7.1
cssutils==1.0.2
drumhat==0.1.0
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==0.12.1
fourletterphat==0.1.0
gitdb2==2.0.3
GitPython==2.1.9
gpiozero==1.4.1
idna==2.6
idna-ssl==1.0.1
itsdangerous==0.24
jedi==0.10.2
Jinja2==2.8
keyring==10.1
keyrings.alt==1.3
MarkupSafe==0.23
mcpi==0.1.1
microdotphat==0.2.1
mote==0.0.3
motephat==0.0.2
multidict==4.3.1
netifaces==0.10.7
numpy==1.12.1
oauthlib==2.0.1
pantilthat==0.0.5
pgzero==1.2
phatbeat==0.1.0
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.38
Pillow==4.0.0
pyasn1==0.1.9
pycodestyle==2.4.0
pycrypto==2.6.1
pygame==1.9.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.4.2
pyOpenSSL==16.2.0
pyserial==3.2.1
python-apt==1.1.0b5
python-magic==0.4.15
pyxdg==0.25
rainbowhat==0.0.2
requests==2.12.4
requests-oauthlib==0.7.0
RPi.GPIO==0.6.3
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.0
sense-hat==2.2.0
simplejson==3.10.0
six==1.10.0
skywriter==0.0.7
smmap2==2.0.3
sn3218==1.2.7
spidev==3.3
thonny==2.1.16
touchphat==0.0.1
twython==3.4.0
unicornhathd==0.0.3
urllib3==1.19.1
Werkzeug==0.11.15
yarl==1.2.4

**Comment by afeena** [comment]
Hi @deanhinson 
Have you run 
`pip install -r requirements.txt`?
As you can see, our requirements is `aiohttp <2.0` and your version is `3.2.1`

**Comment by deanhinson** [comment]
Yes I have, it says that it is install the 1.3.5 version but it still does not change anything when i do pip3 freeze. Do i have to uninstall it and reinstall aiohttp? the output for example:
pip3 install -r requirements.txt 
Collecting aiohttp<2.0 (from -r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/aiohttp/aiohttp-1.3.5-cp35-cp35m-linux_armv7l.whl
Collecting beautifulsoup4 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl
Collecting cssutils (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/6b/15/a9fb9010f58d1c55dd0b7779db2334feb9a572d407024f39a60f44293861/cssutils-1.0.2-py3-none-any.whl
Collecting gitpython (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/88/9c/b462dddb492204417f88d538b0931e87631f2a98afe89842929f4ed9ca5b/GitPython-2.1.9-py2.py3-none-any.whl
Collecting netifaces (from -r requirements.txt (line 5))
  Using cached https://www.piwheels.org/simple/netifaces/netifaces-0.10.7-cp35-cp35m-linux_armv7l.whl
Collecting yarl==0.9.8 (from -r requirements.txt (line 6))
  Using cached https://www.piwheels.org/simple/yarl/yarl-0.9.8-cp35-cp35m-linux_armv7l.whl
Collecting python-magic (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting pycodestyle (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/e5/c6/ce130213489969aa58610042dff1d908c25c731c9575af6935c2dfad03aa/pycodestyle-2.4.0-py2.py3-none-any.whl
Collecting chardet (from aiohttp<2.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting async-timeout>=1.1.0 (from aiohttp<2.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/96/0f/e6357458c87fb4ed8f3df215773f3caad40968f10e05552cbd8bd28415e4/async_timeout-3.0.0-py3-none-any.whl
Collecting multidict>=2.1.4 (from aiohttp<2.0->-r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/multidict/multidict-4.3.1-cp35-cp35m-linux_armv7l.whl
Collecting gitdb2>=2.0.0 (from gitpython->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e0/95/c772c13b7c5740ec1a0924250e6defbf5dfdaee76a50d1c47f9c51f1cabb/gitdb2-2.0.3-py2.py3-none-any.whl
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/e3/59/4e22f692e65f5f9271252a8e63f04ce4ad561d4e06192478ee48dfac9611/smmap2-2.0.3-py2.py3-none-any.whl
Installing collected packages: chardet, async-timeout, multidict, yarl, aiohttp, beautifulsoup4, cssutils, smmap2, gitdb2, gitpython, netifaces, python-magic, pycodestyle
Successfully installed aiohttp-3.2.1 async-timeout-3.0.0 beautifulsoup4-4.6.0 chardet-3.0.4 cssutils-1.0.2 gitdb2-2.0.3 gitpython-2.1.9 multidict-4.3.1 netifaces-0.10.7 pycodestyle-2.4.0 python-magic-0.4.15 smmap2-2.0.3 yarl-1.2.4


pip3 freeze
aiohttp==3.2.1
async-timeout==3.0.0
attrs==18.1.0
automationhat==0.1.0
beautifulsoup4==4.6.0
blinker==1.3
blinkt==0.1.1
buttonshim==0.0.2
Cap1xxx==0.1.3
chardet==3.0.4
click==6.6
colorama==0.3.7
cryptography==1.7.1
cssutils==1.0.2
drumhat==0.1.0
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==0.12.1
fourletterphat==0.1.0
gitdb2==2.0.3
GitPython==2.1.9
gpiozero==1.4.1
idna==2.6
idna-ssl==1.0.1
itsdangerous==0.24
jedi==0.10.2
Jinja2==2.8
keyring==10.1
keyrings.alt==1.3
MarkupSafe==0.23
mcpi==0.1.1
microdotphat==0.2.1
mote==0.0.3
motephat==0.0.2
multidict==4.3.1
netifaces==0.10.7
numpy==1.12.1
oauthlib==2.0.1
pantilthat==0.0.5
pgzero==1.2
phatbeat==0.1.0
pianohat==0.1.0
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.38
Pillow==4.0.0
pyasn1==0.1.9
pycodestyle==2.4.0
pycrypto==2.6.1
pygame==1.9.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.4.2
pyOpenSSL==16.2.0
pyserial==3.2.1
python-apt==1.1.0b5
python-magic==0.4.15
pyxdg==0.25
rainbowhat==0.0.2
requests==2.12.4
requests-oauthlib==0.7.0
RPi.GPIO==0.6.3
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.0
sense-hat==2.2.0
simplejson==3.10.0
six==1.10.0
skywriter==0.0.7
smmap2==2.0.3
sn3218==1.2.7
spidev==3.3
thonny==2.1.16
touchphat==0.0.1
twython==3.4.0
unicornhathd==0.0.3
urllib3==1.19.1
Werkzeug==0.11.15
yarl==1.2.4

**Comment by mzfr** [comment]
@deanhinson yes you will have to remove 3.2.1 version and then install a version lower than 2.0.

**Comment by deanhinson** [comment]
I uninstalled aiohttp and now have version 1.3.5 i also have yarl 0.9.8 but the same problem is still happening where it says no module named 'aiohttp'

**Comment by afeena** [comment]
@deanhinson has the problem been resolved?

**Comment by Sangvin** [comment]
I had the same error
I used sudo when running `pip3 install -r requirements.txt`
then the `sudo python3 clone.py` worked for me

**Comment by glaslos** [comment]
Assuming this has been resolved.
