### ISSUE TITLE
Add possibility to change default directory

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#134]
Right now we always use `/opt/snare/` for storing all the snare files like config and uuid. It might be good to add the possibility to change this folder.

**Comment by tmw9** [comment]
@afeena is this issue still open? if yes, can i take it up?

**Comment by amanjiofficial** [comment]
@afeena @glaslos Is this issue still opened?

**Comment by glaslos** [comment]
There is a pending PR for this issue: https://github.com/mushorg/snare/pull/169
