### ISSUE TITLE
Requests are timing out

### ISSUE THREAD

**Issue by Bartlett-Will** [mushorg/snare#143]
I'm using python 3.4.5 and Debian 16.04.
I cloned chicago.suntimes.com, with a --max-depth of 1, but it doesn't seem to matter what I clone. I am working from behind a firewall, and on a remote server but the port i am serving on and 8090 are open. 

Here is the error log :(
https://pastebin.com/qT3mXZEd

**Comment by afeena** [comment]
Have you used default tanner of your own?
Thanks for reporting a problem, I made a hot fix for you, please check if it works now :)

**Comment by Bartlett-Will** [comment]
Thank you for the timely response. I don't have my own tanner set up yet. Whatever you did seems to work! I'm still getting some interesting behavior. I removed any previously cloned sites and then cloned da-ink.com and chicago.suntimes.com (two popular wordpress websites). When running: 
`sudo python3 snare.py --port 80 --host-ip 0.0.0.0 --page-dir da-ink.com` is can see the request paths and everything seems to be running well. But when i ran `sudo python3 snare.py --port 80 --host-ip 0.0.0.0 --page-dir chicago.suntimes.com` Dorks timeout.
