### ISSUE TITLE
SNARE and hpfeeds

### ISSUE THREAD

**Issue by ahmedkhiar** [mushorg/snare#146]
Does Snare support hpfeeds, urgent please ?

Thank you

**Comment by glaslos** [comment]
There are no plans to support hpfeeds.

**Comment by ChessSpider** [comment]
hi @glaslos I'm looking into mhn and SNARE seems like a great addition as a sensor. I'm curious why hpfeeds is not on the roadmap; [mhn indicate Snare should work with mhn if hpfeeds is supported](https://github.com/threatstream/mhn/issues/535). Thank you for your response

**Comment by glaslos** [comment]
Tanner supports HPFeeds. There is no point in adding HPFeeds to SNARE as it only serves the attack surface. Other honeypot frameworks also utilizing HPFeeds are already including SNARE/Tanner: https://github.com/dtag-dev-sec/tpotce

**Comment by ChessSpider** [comment]
Ah wow, hadn't found that one yet. Thanks! Got some more reading to do
