### ISSUE TITLE
I am getting an error when trying to clone the URL

### ISSUE THREAD

**Issue by Vandenb00m** [mushorg/snare#147]
File "clone.py", line 54
    async def process_link(self, url, level, check_host=False):
it is saying def is causing it.
I tried deleting the file and copying a new one to see if it was spacing but i'm having the same issue. 
I am running on the newest Ubuntu 18.04

Someone Please help!
 - Herc

**Comment by glaslos** [comment]
Can you provide the full stack trace?

**Comment by Vandenb00m** [comment]
That was the only line it was printing out when I ran the copy website command. I decided to start fresh and it worked like a charm!
