### ISSUE TITLE
snare compiling but not working

### ISSUE THREAD

**Issue by jegali** [mushorg/snare#159]
Hi there,

I followed the installation instructions - it compiled, it starts, it shows the snare screen. But if I try to connect from a webbrowser, I get Error 504 - and no response in snare. The error log is empty. I tried to downgrade aiohttp and yarl, but then it does not even compile.  I tried on Debian stretch, Ubuntu 16.04 LTS and Ubuntu 18.04. All systems are up-to-date and are running in a Virtualbox VM. Python version is 3.6.5. I installed as standard user and root. Same result. Do you have any ideas what may be wrong?

Thank you.

**Comment by afeena** [comment]
Hi, have you used your own tanner or you used default? 
It probably was some problems with the default tanner. I checked it and now it should be fine.

**Comment by jegali** [comment]
Hi, I used default configuration. I wanted to change to my own config after I got things to work. I will have another try now.
