### ISSUE TITLE
Can anyone help me setting up Snare?

### ISSUE THREAD

**Issue by cooldude98** [mushorg/snare#163]
I've got Snare perfectly fine running up, but the issue is that I get nothing showing up in the Snare window when I run a nmap scan or a Nikto scan over the hosted server. Where did I go wrong ?

**Comment by viskey98** [comment]
Hi @cooldude98 , There is nothing wrong in the running of snare. The current version of snare is not supposed to show anything (logs or errors) in the snare window. The logs and errors will be stored in `/opt/snare/snare.log` and `/opt/snare/snare.err` respectively. So please check if your logs are stored in the above mentioned files, after you run your nmap or nikto scan. :)
