### ISSUE TITLE
Cannot Run Snare Due to Tanner

### ISSUE THREAD

**Issue by monsterhunterboy98** [mushorg/snare#172]
I Installed Snare successfully.
However I snare not run as it required Tanner. I only was able to successfully clone a web site and when I tried to run snare i got this:
![snare](https://user-images.githubusercontent.com/45062471/48541579-db620380-e8f7-11e8-81e5-2ef0dbf005a4.PNG)

I really do not wish to download Tanner as I am new to Linux and Tanner kept crashing after I installed it and there isn't a good guide I can find online on the installastion steps....

I attempted to download Tanner by running the following commands:
-Retrieving TANNER code
git clone https://github.com/mushorg/tanner.git

-Installing Redis
sudo apt-get install redis-server

-Installation of pip to facilitate easy installation of TANNER
sudo apt-get install python3-pip

 -Installing TANNER
sudo pip3 install -r requirements.txt
sudo python3 setup.py install

Is there a way to run Snare without Tanner?
As based on this video --> (https://www.youtube.com/watch?v=YxtYjU73on8) only Snare is required.

**Comment by monsterhunterboy98** [comment]
Please Help :(

**Comment by viskey98** [comment]
You don't need to run your own Tanner instance, Snare by default will connect to default tanner which runs on http://tanner.mushmush.org:8090/. Make sure your internet connection is working while you start snare.
Or else the default tanner might have been down that time, you can try it again.

**Comment by monsterhunterboy98** [comment]
Thank you for your reply! My snare host is connect to the internet and I still face this issue. This has been an ongoing problem for a week... any idea why? I am running out of time should I switch to an another Web-based honeypot instead of using snare?

![image](https://user-images.githubusercontent.com/45062471/48594110-760b2280-e98a-11e8-92e1-8882d14043eb.png)

**Comment by monsterhunterboy98** [comment]
> You don't need to run your own Tanner instance, Snare by default will connect to default tanner which runs on http://tanner.mushmush.org:8090/. Make sure your internet connection is working while you start snare.
> Or else the default tanner might have been down that time, you can try it again.
 
Any web-application honeypot where I am able to import my own php pages instead of an typicall error webpage?

**Comment by monsterhunterboy98** [comment]
> You don't need to run your own Tanner instance, Snare by default will connect to default tanner which runs on http://tanner.mushmush.org:8090/. Make sure your internet connection is working while you start snare.
> Or else the default tanner might have been down that time, you can try it again.

ty for your help! it was an issue with my internet

**Comment by viskey98** [comment]
@monsterhunterboy98 Glad that it worked :)
