### ISSUE TITLE
Snare was not able to run after cloning my own php files which i used for a web server for my project

### ISSUE THREAD

**Issue by monsterhunterboy98** [mushorg/snare#173]
Snare is up:
![image](https://user-images.githubusercontent.com/45062471/48879834-9c2c3900-ee48-11e8-87dd-f24877467359.png)
![image](https://user-images.githubusercontent.com/45062471/48879858-b108cc80-ee48-11e8-911e-707c73c4e236.png)

I connected to my snare host vm to my apache2 vm where it is used to host my php files. I proceed to clone the the website by running the clone command which I specify the target using  Apache2 VM IP address and the pages was generated at /opt/snare/pages/ as expected.

However, I recievied the following upon running snare:
![image](https://user-images.githubusercontent.com/45062471/48879697-e52fbd80-ee47-11e8-9ef4-63a77c54bdab.png)

Additional Info: I used Mysql and Apache2 to create the website on my apache2 host and the php files are located in thw "www' directory  (I did not use html files)

TY for your help!

**Comment by wangclin** [comment]
I meet the same question. But my KeyError is 'Hash'.I'm waiting for help as well.

**Comment by afeena** [comment]
Am I understand correct that in both cases you have used the address like 
`clone --target 127.0.0.1` ()or any other ip)?

**Comment by wangclin** [comment]
@afeena Thanks for reply.clone --target 192.168.10.xxx. A page in my private network.

**Comment by monsterhunterboy98** [comment]
> Am I understand correct that in both cases you have used the address like
> `clone --target 127.0.0.1` ()or any other ip)?

yes it was an IP. I did this actually -->
![image](https://user-images.githubusercontent.com/45062471/48935572-0de8ad80-ef43-11e8-8804-6549d6fa2f16.png)

**Comment by afeena** [comment]
@monsterhunterboy98 I reproduced your error. I have the same 404 error when I clone with 
`--target http://127.0.0.1`
but when I use just `--target 127.0.0.1` everything works for me.

**Comment by monsterhunterboy98** [comment]
> @monsterhunterboy98 I reproduced your error. I have the same 404 error when I clone with
> `--target http://127.0.0.1`
> but when I use just `--target 127.0.0.1` everything works for me.

Thank you for your reply! I cloned my website again using the --target 192.168.0.1

After that I tried running snare and it was only able to emulate the directory listing of the "www" folder which is the root directory of my php pages for the website. However, when I try to access the pages the browser returned status 404 message.

![image](https://user-images.githubusercontent.com/45062471/49195557-8bd50a80-f3c2-11e8-9db2-1c4923232294.png)

![image](https://user-images.githubusercontent.com/45062471/49195571-95f70900-f3c2-11e8-9c55-0e77a6d4a6d7.png)

**Comment by DanielSpring** [comment]
I've encountered exactly the same issue, I have spent hours trying to sort this out. I have literally tried everything.
![snare](https://user-images.githubusercontent.com/33066562/49282203-79bca000-f486-11e8-910f-1e37df9e3a75.PNG)

**Comment by DanielSpring** [comment]
Yeah I found its very tempremental one minute it works and then next minute it doesn't.

**Comment by DanielSpring** [comment]
> 
> 
> > @monsterhunterboy98 I reproduced your error. I have the same 404 error when I clone with
> > `--target http://127.0.0.1`
> > but when I use just `--target 127.0.0.1` everything works for me.
> 
> Thank you for your reply! I cloned my website again using the --target 192.168.0.1
> 
> After that I tried running snare and it was only able to emulate the directory listing of the "www" folder which is the root directory of my php pages for the website. However, when I try to access the pages the browser returned status 404 message.
> 
> ![image](https://user-images.githubusercontent.com/45062471/49195557-8bd50a80-f3c2-11e8-9db2-1c4923232294.png)
> 
> ![image](https://user-images.githubusercontent.com/45062471/49195622-d22a6980-f3c2-11e8-8201-8e81508b1c6b.png)

I found its very tempremental, one minute it works and then next minute it doesn't.

**Comment by monsterhunterboy98** [comment]
> > > @monsterhunterboy98 I reproduced your error. I have the same 404 error when I clone with
> > > `--target http://127.0.0.1`
> > > but when I use just `--target 127.0.0.1` everything works for me.
> > 
> > 
> > Thank you for your reply! I cloned my website again using the --target 192.168.0.1
> > After that I tried running snare and it was only able to emulate the directory listing of the "www" folder which is the root directory of my php pages for the website. However, when I try to access the pages the browser returned status 404 message.
> > ![image](https://user-images.githubusercontent.com/45062471/49195557-8bd50a80-f3c2-11e8-9db2-1c4923232294.png)
> > ![image](https://user-images.githubusercontent.com/45062471/49195622-d22a6980-f3c2-11e8-8201-8e81508b1c6b.png)
> 
> I find Snare very tempremental, one minute it it hosts the webpage and then next minute it doesn't.

Unfortunately for me, I can't even get my own customize template website running on snare....

**Comment by afeena** [comment]
I will try to reproduce the error when I will have time (hopefully next week). Unfortunately now I am super busy with my study and work. If you find something before, please share :)

**Comment by afeena** [comment]
@monsterhunterboy98 
I guess I know what part of the code causes the problem in your case:
https://github.com/mushorg/snare/blob/master/snare/cloner.py#L49

Here in case of relative links on the webpage, root is concatenated to the link.
Suppose you have 
```
/
/foo
/bar/baz/
```
You root is `127.0.0.1`
Suppose now you on the `127.0.0.1/bar/` page, which has a link the link to `baz`. `baz` will be concatenated with root, bit not the parent, so at the end you will get `127.0.0.1/baz`, which is wrong, because you should have `127.0.0.1/bar/baz`

I need some time to fix it, so feel free to do it if you want :)

**Comment by monsterhunterboy98** [comment]
> @monsterhunterboy98
> I guess I know what part of the code causes the problem in your case:
> https://github.com/mushorg/snare/blob/master/snare/cloner.py#L49
> 
> Here in case of relative links on the webpage, root is concatenated to the link.
> Suppose you have
> 
> ```
> /
> /foo
> /bar/baz/
> ```
> You root is `127.0.0.1`
> Suppose now you on the `127.0.0.1/bar/` page, which has a link the link to `baz`. `baz` will be concatenated with root, bit not the parent, so at the end you will get `127.0.0.1/baz`, which is wrong, because you should have `127.0.0.1/bar/baz`
> 
> I need some time to fix it, so feel free to do it if you want :)

My php pages are connected to a running sql statement that hold info such as images and credentials database as my website have login pages and etc, which all required sql select statements. Is Snare being emulate that portion as well? 

Examples:
https://www.w3schools.com/php/php_mysql_select.asp

**Comment by glaslos** [comment]
The clone tool just takes a snapshot of your static web app content (the HTML generated by your PHP code and database). The content will be completely static (besides JavaScript).
