### ISSUE TITLE
Improve documentation for Snare.

### ISSUE THREAD

**Issue by gauravzqa** [mushorg/snare#181]
the present documentation is very basic and need a better explanation of the concept, working and use cases of Snare which are missing in the current version of documentation available for snare.

**Comment by rnehra01** [comment]
Agree. Feel free to send a PR adding those use cases.

**Comment by rnehra01** [comment]
Just adding some tasks that comes to mind.
- [ ] Add about default tanner in the documentation https://github.com/mushorg/snare/issues/180#issuecomment-468615520

**Comment by amanjiofficial** [comment]
@rnehra01  I want to help fix this issue.

**Comment by rnehra01** [comment]
Go ahead and shoot a PR.
