### ISSUE TITLE
GSoC 2019 - Getting Started

### ISSUE THREAD

**Issue by rnehra01** [mushorg/snare#182]
To get started

- Clone the repo and try to run the tool
- Understand the code through documentation
- The cloner part of snare is NOT perfect, try to clone different website and see if some part of the webpage(images, css, js, realtive path handling) is not properly cloned. (e.g I found #183 )
- Try to complete missing documentation
- Try to add missing tests for methods (E.g https://github.com/mushorg/snare/pull/186#discussion_r264003865)

**Comment by afeena** [comment]
Outdated :)
