### ISSUE TITLE
Improve Error/Information Messages

### ISSUE THREAD

**Issue by rjt-gupta** [mushorg/snare#193]
Currently, the error/information messages are displayed as it is with the output.
I think we can have separate colors for output, errors and information messages. 
ex: [here](https://github.com/mushorg/snare/blob/35846cdc1fd1db069f326a2715df7476d15a7f9b/snare/utils/snare_helpers.py#L92)

What do you guys think?

**Comment by rnehra01** [comment]
Sounds good.

**Comment by afeena** [comment]
duplicates with #213
