### ISSUE TITLE
Suggestion: Add testing information in Readme

### ISSUE THREAD

**Issue by rjt-gupta** [mushorg/snare#195]
There is no information regarding running the tests currently in readme. So, I think adding some directions would be helpful for first-time contributors.

Would like to have opinions from the core devs.

**Comment by rnehra01** [comment]
I guess running tests is standard procedure, present in python docs. But you can add it in snare docs as well, no problem.

**Comment by rjt-gupta** [comment]
I use `pytest` for testing pretty handy. Can I add info for pytest in docs?

**Comment by rnehra01** [comment]
Yeah, I guess it's fine to do that.

**Comment by rjt-gupta** [comment]
Awesome, PR is on the way :)

**Comment by afeena** [comment]
#198 merged
