### ISSUE TITLE
Handle query string in URL while cloning

### ISSUE THREAD

**Issue by shin2903** [mushorg/snare#196]
Currently, snare would return `404 Not found` when serving resources with query string in url .

**Comment by rnehra01** [comment]
@shin2903 Can you provide the steps to regenerate the issue?

**Comment by shin2903** [comment]
## How to reproduce
1. `clone --target https://readms.net --max-depth 1` 
2. `sudo snare --port 8080 --page-dir readms.net`
3. Visit http://localhost:8080/, we see that the cloned page is not rendered correctly

**Comment by rnehra01** [comment]
#199
