### ISSUE TITLE
Cloning non wordpress sites

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#20]
We should try cloning  joomla, drupal, typo3 etc. websites

**Comment by afeena** [comment]
### Joomla

_Original:_
<img width="400" alt="8b6yrg7 1" src="https://cloud.githubusercontent.com/assets/8390928/16850238/a46c0956-4a17-11e6-8260-e630ba09734e.png">

_Cloned:_
<img width="400" alt="knlkist 1" src="https://cloud.githubusercontent.com/assets/8390928/16850267/c45d8d70-4a17-11e6-93a5-3e8d918d557a.png">

**The problem:** relative links


### Drupal:

_Original:_

<img width="400" alt="3gag7af 1" src="https://cloud.githubusercontent.com/assets/8390928/16851702/2814788c-4a1e-11e6-8855-64186da08e61.png">

_Cloned:_

<img width="400" alt="im6qxqq 1" src="https://cloud.githubusercontent.com/assets/8390928/16851721/38d561e0-4a1e-11e6-843c-9389b1b8ab5a.png">


**The problem:** relative css links (e.g. rss has absolute link)

### Typo3

_Original:_
<img width="400" alt="dguhifj 1" src="https://cloud.githubusercontent.com/assets/8390928/16852446/9e72ecd6-4a21-11e6-89a5-c7c6630fbe74.png">

_Cloned:_

<img width="400" alt="rxpbu5a 1" src="https://cloud.githubusercontent.com/assets/8390928/16852462/b18fdda6-4a21-11e6-8420-3b22133e873e.png">

**The same problem**

**Comment by glaslos** [comment]
Fixed with 7bb381e
