### ISSUE TITLE
Unable to access the cloned website.

### ISSUE THREAD

**Issue by Waseem-farooqui** [mushorg/snare#206]
I have cloned the web site using 
`sudo clone --target https://www.news18.com/india/ --max-depth=1`.

Now when I run the the following ` sudo snare --port 8080 --page-dir www.news18.com`

It give me this error.

`sensor@sensor:~/snare$ sudo snare --port 8080 --page-dir www.news18.com

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

Can't connect to tanner host http://tanner.mushmush.org:8090/version
sensor@sensor:~/snare$
`

Even the port 8080 is not listening.

Why it looks for the tanner of MushMush ?

**Comment by afeena** [comment]
@Waseem-farooqui Hi, it's the problem with default tanner instance. You can run your own tanner instance following instructions in tanner https://github.com/mushorg/tanner and run snare with `--tanner <your tanner instance ip>` parameter

**Comment by Waseem-farooqui** [comment]
Tried with this but still 
`sudo snare --port 8080 --page-dir www.news18.com --tanner localhost`

```
serving with uuid ac5e931d-4340-4add-b26c-23a576cbfeb5
Debug logs will be stored in /opt/snare/snare.log
Error logs will be stored in /opt/snare/snare.err
Traceback (most recent call last):
  File "/usr/local/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 200, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 92, in start
KeyError: '/status_404'
you are running the latest version
```

**Comment by glaslos** [comment]
The official Tanner is up again :+1:

**Comment by Waseem-farooqui** [comment]
@glaslos means ?

**Comment by glaslos** [comment]
https://github.com/mushorg/snare/search?q=KeyError%3A+%27%2Fstatus_404%27&type=Issues

**Comment by Waseem-farooqui** [comment]
I have seen and tried this to remove all the pages and clone the website again but it didn't worked.

**Comment by glaslos** [comment]
What clone command are you using?

**Comment by Waseem-farooqui** [comment]
`sudo clone --target http://www.hec.gov.pk`

While cloning it throw lot of errors like  `ERROR   Property: Invalid value for "CSS Level 2.1" property: none [10:186095: background-color]`

**Comment by glaslos** [comment]
you should be using only the domain name, e.g. `hec.gov.pk` see `clone -h`. @afeena maybe we should make this less error prone 😬
