### ISSUE TITLE
Improve printing information with colors

### ISSUE THREAD

**Issue by rnehra01** [mushorg/snare#213]
Change the current print function with the new print_color method added #208

**Comment by steve7158** [comment]
I would like to work on this issue can please. If possible can you please point me to a starting point
 Thank you

**Comment by steve7158** [comment]
And also which type of information would like to be colored, as #208 was for errors
Thank you

**Comment by steve7158** [comment]
> And also which type of information would like to be colored, as #208 was for errors
> Thank you

never mind i have figured it out

**Comment by steve7158** [comment]
#250

**Comment by glaslos** [comment]
Closed with #252
