### ISSUE TITLE
page-dir error

### ISSUE THREAD

**Issue by lnarcy** [mushorg/snare#217]
im getting an "--page-dir: http://www.isep.ipp.pt does not exist" error when I run
$sudo snare --page-dir http://www.isep.ipp.pt

The clone command I used is $sudo clone --target http://www.isep.ipp.pt

**Comment by rjt-gupta** [comment]
I guess you only need this - `sudo snare --page-dir www.isep.ipp.pt`.

**Comment by rjt-gupta** [comment]
@lnarcy Is your issue resolved or need some extra help? :)
