### ISSUE TITLE
How to Print Sensor Name or IP in the log file as Glastopf does

### ISSUE THREAD

**Issue by suhiherazeN1N** [mushorg/snare#219]
How to Print Sensor Name or IP in the log file as Glastopf does ? @glaslos or anyone

**Comment by afeena** [comment]
@suhiherazeN1N I don't know how it is done in Glastopf, but you can see sensor uuid when you run snare
`serving with uuid <UUID>`

**Comment by glaslos** [comment]
I assume this is answered.
