### ISSUE TITLE
Problem serving pages

### ISSUE THREAD

**Issue by dimitoglou** [mushorg/snare#229]
After a successful installation and testing,  I am able to see in the logs attempts to the IP and port. But am having trouble serving "real" web pages. My /opt/snare/pages/example.com is there but I get "500 Internal Server Error" from the browser. My goal is to replace example.com with something more "enticing" but adding a valid index.html file does not seem to make a difference. Am I missing something? Thank you!

**Comment by rjt-gupta** [comment]
You have to clone the real web pages of the system using the ``cloner`` first (changing the only index will not help). It will create a separate directory of the real application in /opt/snare/pages which you can serve using ``snare``.
