### ISSUE TITLE
Re-clone the site if content is updated

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#23]
I think it will be great if we can detect the updates on the original site and initialize re-cloning process to keep our honeypot up to date, what do you think?

**Comment by glaslos** [comment]
There are a couple of things you have to consider:
- If we don't control the original, someone can make us clone malicious content.
- We want to avoid copying the internet
- We have to consider copyrights.

I think one option could be serving the pages from TANNER. So SNARE could ask TANNER for a web site to serve. I think your idea is generally good, but it's probably too early at the moment.

**Comment by mzfr** [comment]
@glaslos Can you explain a bit on what that "malicious content" could be ?
and in what way copyrights can be a problem ?

**Comment by glaslos** [comment]
Malicious content could be anything distributed via HTTP :) but think things like a malicious coin miner. Regarding copyright, you can't just clone someones web page or content and then provided it on your web page.

**Comment by afeena** [comment]
Users should take care of cloning by themselves
