### ISSUE TITLE
Feature Request: Support for TLS

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/snare#236]
Most websites are running on TLS today which attackers will most likely to focus on. Would be great if Snare had the option of using TLS.

**Comment by glaslos** [comment]
@t3chn0m4g3 why not run a proxy like caddy with TLS and auto-renew in front of your SNARE instances? I would prefer to keep the SNARE complexity low.

**Comment by t3chn0m4g3** [comment]
@glaslos Thanks for your feedback. Yes this is possible of course, however if you [look here](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/tanner/docker-compose.yml) you will hopefully agree that introducing Caddy (which is [great](https://twitter.com/marco_ochse/status/1236044834286309378)) will only introduce another point of failure and increase complexity with regard to analyzing logs / events in just one place.
However I cannot really assess how complex TLS implementation into SNARE would look like. Please give it some thought, will trust your opinion on this.

**Comment by glaslos** [comment]
it kind of depends on how we want to implement #36 If SNARE does multi site, then we could also do TLS in SNARE, if we recommend with one SNARE instance per site, then it would make more sense to also do TLS in the proxy doing the vhost.

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback. Is #36 part of GSoC 2020?

**Comment by glaslos** [comment]
Probably, @afeena is quite open and will plan the features with the student.

**Comment by afeena** [comment]
I think it might be a good task to work on :) I am definitely up for spending some time on it

**Comment by t3chn0m4g3** [comment]
Sounds great :) Thx.

**Comment by Parth1811** [comment]
@t3chn0m4g3 @glaslos I am planning to include this in my GSoC proposal, I was thinking of adding TLS without doing the multi-site support. I wanted to know what problems I will run into, and what approach will you recommend to take.

**Comment by glaslos** [comment]
Generally any site will need a separate certificate, so I think you are fine with suggesting this for a single domain approach. Would be nice if you would add some thoughts on how to scale to multiple sites.
I'd like to see a solution where certificate renewal is taken care of automatically. Check out how this works for Let's Encrypt.

**Comment by t3chn0m4g3** [comment]
@glaslos @Parth1811 I do not think every site needs its own cert since Let's Encrypt [supports ](https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579) wildcard certificates with [certbot 0.22.0](https://community.letsencrypt.org/t/how-to-issue-acmev2-wildcard-with-certbot-0-22-0/55657).
However there is a number of users running their honeypot on DSL with dynamically assigned IP / DDNS which will not allow for official certs. At least out of the box there should also be support for a selfsigned cert. While Let's Encrypt supports [localhost ](https://letsencrypt.org/docs/certificates-for-localhost/)certs which would be OK for that I could not find support for wildcards in that regard.

**Comment by Parth1811** [comment]
@t3chn0m4g3 @glaslos Regarding wildcard certificates, Let's Encrypt only supports in  ACMEv2 for which you have to get validated using the DNS-01 challenge which would be difficult with dynamic IP/DDNS. 
For the localhost what is understood is we have to generate a private key and self-signed certificate and configure the locally trusted roots.

So my plan of action would be to provide two methods of certificate generation:-
1. Locally for the localhost and local networks
2. Using Let's Encrypt for deployment servers

Also, I think each site will need a different certificate. We can do a certificate management task at the beginning of each SNARE instance for different sites. Correct me if I got something wrong :)

**Comment by glaslos** [comment]
Yeah, wildcards only solves the problem only for subdomains, I'm usually setting up multiple FQDN. Do some research on how difficult this is in Python and let me know what you find.
