### ISSUE TITLE
GSoC 2020

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#248]
# Here is the short guide for upcoming GSoC 2020!

**Slack**: [gsoc-slack.honeynet.org ](url)
_Mentor:_ @afeena 
_Backup mentor:_ @glaslos 

## How do I start?
* Join our GSoC channel #2020-snare
* Follow the quick-start and run the code
 * Play with the tool! Try different stuff/attacks/crawlers
* Found a bug? → Create an issue 
* Go through existing issue to get the idea of the project problems and try to think about solution
* Do you know how to fix something? Great! → SUBMIT A PULL REQUEST

## What should I know to successfully participate?
* **Python3**. You should really know it. 
* **Git**. https://try.github.io/
* **Databases**, SQL, Postgres
* **InfoSec**: you can start with The Honeynet Project https://www.honeynet.org/papers/ or look up 
       OWASP materials https://owasp.org/www-project-cheat-sheets/
* **Network monitoring**. Install Wireshark and explore
* Know the better materials for infosec? Comment!

## How to write proposal/which tasks should I include
There are some tasks which we really want to be finished during this summer (list by priority). I expect that these tasks will take most of the time:
* Replace Redis with other database in TANNER
     * https://github.com/mushorg/tanner/issues/322
* Making cloner great (again) in SNARE
    * Regarding cloner: Ideally, it should be re-written completely, as a result, also storing and serving web-pages will be changed. So it’s a really big task, which should be decomposed properly. And  it should have some pre-work done (research, etc). Current system doesn’t support websites with client-side rendering, so we should think about using headless-browser
    * https://github.com/mushorg/snare/issues/215
    * https://github.com/mushorg/snare/issues/183
* Other tasks are optional and we are really open, so if you have some great features in mind - don't hesitate to add it
* Time estimation is a key: try to fairly estimate time for each task. Remember: it's better to be ahead of the schedule than behind.
* You can also look up the GSoC submission results from previous years here 
    * https://github.com/mushorg/tanner/wiki
* Use template from previous years
    * https://docs.google.com/document/d/18abX5l4HN5v37QAh5SKgHtlXhhINKEte49hmqzwE2mM/edit?usp=sharing 

## Is having a contribution in SNARE/TANNER a prerequisite?
* We don't have strong requirements on contribution, but it will help us to evaluate your application. Take it as a possibility to show your coding skills.
* Contribution is not only pull requests, you can also submit a bug or review other student's pull requests :)

## Something is not covered? 
* comment here!
* Or: ping us in slack channel (please try to ask in our channel, your questions might be interesting for other students)

**Comment by afeena** [comment]
### Issues related to cloner:
* https://github.com/mushorg/snare/issues/183
* https://github.com/mushorg/snare/issues/230

**Comment by rjt-gupta** [comment]
Small task suggestion  - https://github.com/mushorg/tanner/issues/381
