### ISSUE TITLE
Using multi threading to make cloning faster

### ISSUE THREAD

**Issue by steve7158** [mushorg/snare#257]
I was just reading through the code when i realized we are cloning in 3 parts of a webpage, namely 
1. find all relative links
2. find all images and scripts
3. find al action elements 
one by one, so instead can we use 3 threads to carry out the downloading of the three tasks simultaneously. I know it would involve rewriting a big chunk of the code but it can significantly increase the cloning speed.

**Comment by afeena** [comment]
@steve7158 Cloner is written in async way, so we don't need threads, but I agree that there is a room for improvements and optimization, to ensure that everything is really executed in async way
If you are not familiar with async, please read e.g. https://medium.com/velotio-perspectives/an-introduction-to-asynchronous-programming-in-python-af0189a88bbb

**Comment by steve7158** [comment]
Thank you @afeena i will surely look into it :+1: . I will close this issue as this is no longer valid.
