### ISSUE TITLE
Cannot publish cloned Site

### ISSUE THREAD

**Issue by martinzeifang** [mushorg/snare#269]
Hey, 

I tryed to test snare: 

`sudo clone --target facebook.de --max-depth=1

    ______ __      ______ _   ____________
   / ____// /     / __  // | / / ____/ __ \
  / /    / /     / / / //  |/ / __/ / /_/ /
 / /___ / /____ / /_/ // /|  / /___/ _, _/
/_____//______//_____//_/ |_/_____/_/ |_|

    
/ Logs will be stored in /opt/snare/clone.log|
------------------------------------>SUMMARY<------------------------------------
        Total number of URLs cloned: 102
        Time elapsed: 0:00:40.441358
        Cloned directory: /opt/snare/pages/facebook.de
----------------------------------------------------------------------------------
...:~/Software/snare$ sudo snare --port 8080 --page-dir facebook.de
`
cloning is working without an error. But I can't publish the site: 

`sudo snare --port 8080 --page-dir facebook.de

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/
    
Can't connect to tanner host http://tanner.mushmush.org:8090/version
`

**Comment by mzfr** [comment]
@martinzeifang Looks like the issue is with the global tanner instance. It is recommended that you use to start your own tanner instance and then use that for the snare.

You can use `--tanner <IP/domain of your tanner instance>`.

So if you start tanner on your localhost then you can run snare like:

```
sudo snare --port 8080 --page-dir facebook.de --tanner localhost
```
