### ISSUE TITLE
Cannot clone websites

### ISSUE THREAD

**Issue by teamthanos** [mushorg/snare#270]
I am running Ubuntu 18.04 on VMware and just tried to set up snare, but I am getting Traceback errors when cloning a website. 

Python is 3.6.9 and I followed all steps mentioned in the "Getting Started" section, 
 
I get a lot of "Warnings" and "Errors" as well, but the "Traceback" at the end gives me the impression that it's really failing. 

The logs are here https://pastebin.com/ufLR9gd0

Can anyone please help?

**Comment by lordlabuckdas** [comment]
I'm not able to replicate this issue.
The warnings and errors can be ignored, they show information about the CSS validation of the site.
Also, it looks like the URL that you entered in the logs is invalid. `<` would refer to the redirection operator there.
Can you try the `clone` command with another URL and check if it is working properly?
