### ISSUE TITLE
Python support beyond 3.6/3.7

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/snare#271]
I just noticed, as soon as I run Snare with Python > 3.7 Snare does not respond to HTTP requests and the socket remains closed but no error message is given.

**Comment by mzfr** [comment]
Yes that is the known issue. https://github.com/mushorg/snare/issues/244

**Comment by t3chn0m4g3** [comment]
@mzfr Thanks 😊 I was only looking at the open issues. May bad.
