### ISSUE TITLE
Can't connect to tanner host http://tanner.mushmush.org:8090/version

### ISSUE THREAD

**Issue by rheabonnerji** [mushorg/snare#273]
Internet connected and working but the service seems down. Would be great if the service can be restarted or turned on if turned off.

**Comment by lordlabuckdas** [comment]
Currently, [tanner.mushmush.org](http://tanner.mushmush.org:8090/version) is online. Alternatively, you can try setting up your [own tanner instance](https://github.com/mushorg/tanner/#steps-to-install-tanner).
