### ISSUE TITLE
Not able to load snare website

### ISSUE THREAD

**Issue by lordlabuckdas** [mushorg/snare#274]
I've exactly followed the docs in setting up my snare and personal tanner instances, but I'm unable to get the [snare site](http://127.0.0.1:8080) up and running.

I just the get ascii art of snare, then sometime later, a `TimeoutError` or `Can't connect to tanner host http://0.0.0.0:8090/version` when i close my tanner instance.

Netstat doesn't show snare to be running (but tanner, php sandbox and redis are).

The website for tanner in my browser (firefox), keeps on loading - probably waiting for a connection from snare.

Furthermore I'm not able to access tannerweb and tannerapi in the browser as well.

I've tested this on Ubutnu 20 and Kali 2020, both in virtual environment and base environment.

I have attached the pastebin links of my `snare.log`, `tanner.log` and `tanner.err` for reference. (`snare.err` is empty)

[tanner.log](https://pastebin.com/kqF8AhUQ)

[tanner.err](https://pastebin.com/WdgqNrYb)

[snare.log](https://pastebin.com/w76AbBWz)

**Comment by mzfr** [comment]
@lordlabuckdas umm looks like you are using python3.8 so please use python3.7 to get everything working.

**Comment by lordlabuckdas** [comment]
thanks @mzfr , that worked!
