### ISSUE TITLE
Snare TLS/SSL support

### ISSUE THREAD

**Issue by Fosocles** [mushorg/snare#276]
Hi.

I was wondering whether or not there are any plans of adding TLS/SSL support to SNARE. I am trying to host a SNARE instance on port 443/HTTPS, but I am unable to start it properly: it throws some certificate errors, if I remember correctly and I don't know where/how to specify a path to any certs/CA files.

Thanks in advance.

**Comment by mzfr** [comment]
@Fosocles We already have an open issue for this. Please see the discussion on #236

**Comment by Fosocles** [comment]
I thought I've seen a similar topic, but couldn't find it. 
Thanks for the answer.
