### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by Nicocimbali** [mushorg/snare#277]
Hi,
Afert i cloned a website and launched snare, when i visited it on 127.0.0.1:8080  i see a blank page. 
Do you know why?
These are the commands that i used:
sudo clone --target http://zero.webappsecurity.com/index.html
sudo snare  --port 8080 --page-dir zero.webappsecurity.com
I used python 3.7.0

**Comment by lordlabuckdas** [comment]
Can you comment the [pastebin](https://pastebin.com/) links to your `snare` and `cloner` logs?
Also, check if port 8080 is up and running using `sudo netstat -tulnp`

**Comment by afeena** [comment]
please refer to the #278  or create the new issue.

Thanks
