### ISSUE TITLE
fail to clone web page

### ISSUE THREAD

**Issue by Haotian-Shi-cyber** [mushorg/snare#278]
when i try to clone, it alerts me "aiohttp" is not installed.
after then, use "python3.6 -m pip install aiohttp".. and i got this
![image](https://user-images.githubusercontent.com/62081228/100115630-a7b4ff00-2e6a-11eb-972d-c418229f5e2c.png)
![image](https://user-images.githubusercontent.com/62081228/100115674-b3a0c100-2e6a-11eb-84cd-1976ff439f10.png)
![image](https://user-images.githubusercontent.com/62081228/100115715-c0bdb000-2e6a-11eb-849e-a9de2bfdc652.png)
couldn't find any solutions

**Comment by lordlabuckdas** [comment]
Can you try running `sudo apt install python3.6-dev` and run the setup again?

**Comment by lordlabuckdas** [comment]
Can you try running `sudo apt install python3.6-dev` before the setup?

**Comment by Haotian-Shi-cyber** [comment]
just found it is ./bin/clone right? not built-in command... its ok, is there requirements for pages im going to clone? eg, must be http and not for https?

**Comment by lordlabuckdas** [comment]
`./bin/clone` contains the raw file for the cloner which will be built into a pip module by `setuptools` in `setup.py`.
The recommended way to set up and use Snare (and Cloner) is to run `[sudo] python setup.py install` and then use the `clone` command directly.
Also, I don't think there are no requirements regarding the protocol (http/https), you can clone any site.

**Comment by Haotian-Shi-cyber** [comment]
i cloned youtube.com but still can't access page. 
![image](https://user-images.githubusercontent.com/62081228/106355450-d5e20f80-62ef-11eb-9080-d68ea626e1d6.png)

**Comment by Haotian-Shi-cyber** [comment]
every time i cloned a page, it got so many warnings and errors, is there anything wrong
![Uploading image.png…]()

**Comment by Haotian-Shi-cyber** [comment]
every time i cloned a page, it got so many warnings and errors, is there anything wrong
![image](https://user-images.githubusercontent.com/62081228/106358290-49414c80-6303-11eb-99ed-75c1fab92dd2.png)

**Comment by mzfr** [comment]
@Haotian-Shi-cyber Please post the output of the log files.

**Comment by Haotian-Shi-cyber** [comment]
![image](https://user-images.githubusercontent.com/62081228/106439862-16689700-6470-11eb-9f5b-bf3a4fc8ab57.png)
some examples

**Comment by mzfr** [comment]
@Haotian-Shi-cyber it would be nice if you can post the complete output on Pastebin and then give the link. The screenshot you provided doesn't give much information.

**Comment by Haotian-Shi-cyber** [comment]
http://pastebin.com/28XTaM98

**Comment by afeena** [comment]
@Haotian-Shi-cyber most of the warnings come from the css parsing library, it is not the from cloner itself. Also please remember that cloner has really limited functionality, so not every page can be successfully cloned.

Regarding the page serving, could you please provide the snare logs instead of the cloning logs? From your cloning logs I can not say anything regarding your problem with page access.

Thanks

**Comment by aabulaeva** [comment]
> i cloned youtube.com but still can't access page.
> ![image](https://user-images.githubusercontent.com/62081228/106355450-d5e20f80-62ef-11eb-9080-d68ea626e1d6.png)

Hello,
i have the same issue
do you find a solution ?
thanks

**Comment by Haotian-Shi-cyber** [comment]
hi,

no, i gave it up.

thanks

**Comment by mzfr** [comment]
I just tested this and had no issues except the following error:

```
Traceback (most recent call last):                                                                                                                           
  File "/home/mzfr/dev/snare/venv/bin/clone", line 4, in <module>                                                                                            
    __import__('pkg_resources').run_script('Snare==0.3.0', 'clone')                                                                                          
  File "/home/mzfr/dev/snare/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script                                           
    self.require(requires)[0].run_script(script_name, ns)                                                                                                    
  File "/home/mzfr/dev/snare/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1479, in run_script                                          
    exec(script_code, namespace, namespace)                                                                                                                  
  File "/home/mzfr/dev/snare/venv/lib/python3.10/site-packages/Snare-0.3.0-py3.10.egg/EGG-INFO/scripts/clone", line 81, in <module>                          
  File "/home/mzfr/dev/snare/venv/lib/python3.10/site-packages/Snare-0.3.0-py3.10.egg/EGG-INFO/scripts/clone", line 67, in main                              
UnboundLocalError: local variable 'end' referenced before assignment
```

That should be fixed https://github.com/mushorg/snare/pull/320
