### ISSUE TITLE
Support for Python 3.8.x

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/snare#281]
While Snare builds from latest master and starts up fine using Python 3.8.x it does not allow for connections being established. Unfortunately there is literally nothing logged in `.err` or `.log`.

Let me know if you can reproduce or how / if I can provide debug logs.

**Comment by mzfr** [comment]
Yeah this is kind of known(https://github.com/mushorg/snare/issues/244), even though I never investigated it deeply.

**Comment by t3chn0m4g3** [comment]
Thanks for the swift feedback! Let me know if I can support with logs.
