### ISSUE TITLE
Snare container is grabbing proxy internal IP as remote_addr but Tanner is grabbing Real IP address.

### ISSUE THREAD

**Issue by GcmMiguel** [mushorg/snare#284]
Hello,

I am deploying a honeypot behind a nginx proxy trying to achieve the following logic:

- If HTTP request asks for a legit host (i.e.: legit domain as host) -> proxy pass to legit HTTP server
- If HTTP request is not requesting a legit domain (i.e.: IP as host) -> proxy pass to honeypot HTTP server (using tanner & snare for port 80)

Everything is already set, up and running. Working as expected, except that Snare is not getting the reail attacker IP address, which is relevant when you are analyzing attackers with a honeypot. I tried several workarounds like declaring network_mode host or playing with iptables .

During my investigation I realized tanner headers were grabbing properly the real attacker IP address (X.X.X.54 in this case), while snare was grabbing the proxy's internal IP (192.168.X.X in this case).
Please find below the entries in app logs for the same controlled request I performed (I removed unrelevant information)

tanner/log/tanner_report.json:
{"method": "GET", "path": "/resources/foo.png", "headers": {**"x-real-ip": "X.X.X.54",** "host": "MYHOSTGOESHERE", **"x-forwarded-for": "X.X.X.54", "remote_addr": "X.X.X.54"**, "connection": "keep-alive", "user-agent": "Mozilla/5.0 (Linux; Android 11; IN2023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Mobile Safari/537.36", "peer": {**"ip": "192.168.X.X",** "port": 41320}, "status": 200, "cookies": {}, "response_msg": {"version": "0.6.0", "response": {"message": {"detection": {"name": "index", "order": 1, "type": 1, "version": "0.6.0"}, "sess_uuid": ""}}}, "timestamp": "2021-03-12T10:45:20.666939"}

snare.log:
2021-03-12 10:45:20 INFO:aio**http.access:log: 192.168.X.X** [12/Mar/2021:10:45:20 +0000] "GET /resources/foo.png HTTP/1.1" 200 24414 "http://MYHOSTGOESHERE/" "Mozilla/5.0 (Linux; Android 11; IN2023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Mobile Safari/537.36"

Is there something I can do so Snare can grab the real remote_addr?

Thank you!

**Comment by glaslos** [comment]
The correct behavior from Snare would be to check for the X-Forwarded-For header and use that instead. Are you comfortable with creating a Pull Request with that change? I'm happy to assist if you need help.
