### ISSUE TITLE
Error with page formating and handling request

### ISSUE THREAD

**Issue by d4rksou1** [mushorg/snare#30]
Hi,
just tried out this honeyPot. seems very promissing, but i'm having 2 major issues:
1- when i try clone a website I get A few errors in some css, js and jpeg files, what cause the page to break down. I've tried to first clone the site with httracker then put up a webserver locally and clone it again with clone.py, the site seems a little more legit but takes me to the next problem;
2- I get a bunch of errors due handling requests. and only about 20% of the site is available.

I've tried this in 3 diferent sites with diferent constructions so i decided to ask if there are some issue related with this.

just leave the error
"Request path: /indexc86f.html?page=contacto
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 285, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 170, in handle_request
    event_result = yield from self.submit_data(data)
  File "snare.py", line 122, in submit_data
    raise e
  File "snare.py", line 120, in submit_data
    r.release()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 564, in **exit**
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
"

is there any trick to clone the site?

regards

**Comment by afeena** [comment]
Can you give me some more info? Which sites did you clone? Did you use your own TANNER or default? How did you start snare? Timeout error occurs when something wrong with TANNER

**Comment by d4rksou1** [comment]
thanks for the prompt reply.

to be honest i didnt understand how tanner comunicate with snare and vice versa so probably it used the default.

I'm using ubuntu server 16 and installed snare and tanner on the same machine using the README.md as a guide.
and tried to clone the following websites:
http://www.isep.ipp.pt
http://www.academias.isep.ipp.pt
http://knowhowbuilders.com

the VM with the ubuntu has 1Gb of ram and 1 Core for the processor at 2,4GHz 

probably i'm been a noob and there are some docs that i didn't find but if you can guide me I would apreciate.

Thanks
best regards

**Comment by afeena** [comment]
Do you start SNARE with ``--tanner <ip:port>`` parameter?
If you do, can you please give me the logs? Run in your tanner directory: ``tail tanner.log``

**Comment by d4rksou1** [comment]
Thank you the timeout problem was solved using the local tanner correctly but still having problems with the cloner... 
some of the errors:

[Errno -2] Cannot connect to host imgs:80 ssl:False [Can not connect to imgs:80                                                                                                                      [Name or service not known]]
path:   name:  /bg.gif
[Errno -2] Cannot connect to host imgs:80 ssl:False [Can not connect to imgs:80                                                                                                                      [Name or service not known]]
path:   name:  /javascript:fbht('fbrp_ht_56').html
path:  /modules/JQueryTools/lib/css/../jquery.fancybox/ name:  jquery.fancybox-1                                                                                                                     .3.4.css
WARNING Property: Unknown Property name. [327:58: filter]
ERROR   PropertyValue: No match: ('CHAR', ':', 327, 72)
ERROR   PropertyValue: Unknown syntax or no value:  progid:DXImageTransform.Micr                                                                                                                     osoft.AlphaImageLoader(src='fancybox/fancy_close.png', sizingMethod='scale')
ERROR   CSSStyleDeclaration: Syntax Error in Property: filter: progid:DXImageTra                                                                                                                     nsform.Microsoft.AlphaImageLoader(src='fancybox/fancy_close.png', sizingMethod='                                                                                                                     scale')
WARNING Property: Unknown Property name. [329:61: filter]
ERROR   PropertyValue: No match: ('CHAR', ':', 329, 75)
ERROR   PropertyValue: Unknown syntax or no value:  progid:DXImageTransform.Micr                                                                                                                     osoft.AlphaImageLoader(src='fancybox/fancy_nav_left.png', sizingMethod='scale')
ERROR   CSSStyleDeclaration: Syntax Error in Property: filter: progid:DXImageTra                                                                                                                     nsform.Microsoft.AlphaImageLoader(src='fancybox/fancy_nav_left.png', sizingMetho                                                                                                                     d='scale')


but now I can do some tests pre cloning with httrack and recloning locally with the clone.py
Thank you
Congrats with the project!!

**Comment by afeena** [comment]
Thanks for submitting the issue! :)  Now I'm going to solve the problem with cloning

**Comment by afeena** [comment]
Since we use new cloner, this error is not relevant anymore.
