### ISSUE TITLE
Test Tanner connection on startup

### ISSUE THREAD

**Issue by glaslos** [mushorg/snare#31]
We should check on startup if we have a working connection to Tanner. Stop Snare if Tanner is not reachable. Run into this problem when sitting behind a wifi with a portal.

**Comment by afeena** [comment]
If user has local TANNER in parameter, but it is unreachable, what we should do? 
- Stop SNARE if local TANNER unreachable and notify the user 
- Check default (if available - notify that we use default TANNER) 
- Stop SNARE only if both (local and default TANNERs) are unreachable

**Comment by glaslos** [comment]
I think stopping SNARE if the provided TANNER is unreachable is the correct way to go.

**Comment by glaslos** [comment]
Closed with #38
