### ISSUE TITLE
Link to tanner.mushmush.org:8090/version stops SNARE

### ISSUE THREAD

**Issue by JBar2K** [mushorg/snare#312]
Following the directions posted for installation of SNARE. Cloned my site successfully, but when running snare I receive the following error, "Can't connect to tanner host http://tanner.mushmush.org:8090/version" and then SNARE exits. Ran sudo apt update just in case, but everything is current.
Tried accessing http://tanner.mushmush.org:8090/version with a web browser, but page timed out. Tried http://tanner.mushmush.org which also timed out.

Below is a copy of the terminal session

rick@slimpickins:~/snare$ sudo snare --port 8080 --page-dir bartonfam.com
   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/
    
Can't connect to tanner host http://tanner.mushmush.org:8090/version
rick@slimpickins:~/snare$ sudo apt update
Hit:1 http://ports.ubuntu.com/ubuntu-ports impish InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports impish-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports impish-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports impish-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

**Comment by Lionel98** [comment]
same issue

**Comment by GitRayk** [comment]
I have the same issue.
Do you find a solution ?

**Comment by mzfr** [comment]
The problem is that the Tanner host you are using isn't running at all. That host is down, which might cause issues with a snare. 

The best way to run snare when the public tanner instance is down is to run your own tanner host.
