### ISSUE TITLE
(56) Illegal or missing hexadecimal sequence in chunked-encoding

### ISSUE THREAD

**Issue by Foxsden13** [mushorg/snare#317]
Hey guys,
does anybody have an idea on how to fix the problem I have?
I set up my own cloned website (only basic html) via snare and clone on the tpot server.
When I try to open the site in my browser it only shows a blank window.
Trying to open the website with curl it says
(56) Illegal or missing hexadecimal sequence in chunked-encoding

I was able to clone and open the website example.org in my browser. Everything worked fine.

Thank you very much in advance :)

**Comment by mzfr** [comment]
This(https://github.com/mushorg/snare/blob/main/docs/faq.md#frequently-asked-questions) should help you fix your problem

**Comment by Foxsden13** [comment]
Good evening,
I started fresh and recreated a server from a snapshot I did a month ago.
It contains a fresh installation of the standalone tpot by telekom.
Everything works fine. Snare and Tanner are showing some random cms sites.

The first step I did was cloning a wordpress website from the internet:
![cloner](https://github.com/mushorg/snare/assets/116648289/b448c057-247a-4969-a687-a07827f96f6e)

After that I used scp to move the cloned folder with the 34 urls and the meta.json file onto my server where the tpot ist running.
Then I modified the Dockerfile in /opt/tpot/docker/tanner/snare:
![2](https://github.com/mushorg/snare/assets/116648289/551a51c9-7bd7-4c38-baa2-12646e2e58c7)

And I also modified the Dockerfile in /home/******/tpotce/tanner/snare/:
![1](https://github.com/mushorg/snare/assets/116648289/38cdd5b9-72fe-4b8d-86ef-560508a9ada5)

When I restart the tpot via systemctl every docker container fires up fine:
![docker](https://github.com/mushorg/snare/assets/116648289/f5a965ac-c93a-42f7-835d-c15902beffa5)

When I try to reach the website in my browser on port 80 there still is only a blank white page. I can't even right click it.

I dont know how to check if the tpot is using the correct version of snare, but I guess so because it worked in the beginning.

I checked the container running tanner:
![tanner](https://github.com/mushorg/snare/assets/116648289/9b0ea214-7c0e-4b79-a245-eaf51d32279a)

and also the tanner log file:

![tanner log](https://github.com/mushorg/snare/assets/116648289/27f63059-aa2b-448d-8b68-ad8478b4cc4b)

Sorry for that long post, but I am running out of ideas :/
I hope you can help me.

Best regards!
