### ISSUE TITLE
How to report events  to syslogs or dashboards

### ISSUE THREAD

**Issue by santiago92** [mushorg/snare#33]
Hi, I'm Santiago, I'm doing research work. I would like to know how to generate reports with snare / tanner? Because, I used tool for months and I can't find How to report events on syslogs or  dashboard, such as MHN.
Greetings.

Contact : santi.alasia92@gmail.com

**Comment by afeena** [comment]
Hi, Santiago. We have logging system on the TANNER side. TANNER store the events and sessions. So, please, can you provide me some more info: do you use your own TANNER or default?

**Comment by santiago92** [comment]
Hi , I run SNARE with TANNER but i can`t find how to log events in file or databases. What are the sessions in the new TANNER realese?

**Comment by afeena** [comment]
By default, TANNER store logs in tanner.log file (in your TANNER source directory). And sessions stored in Redis. You can access sessions via api (it's a bit stupid, but you can access sessions via <tanner_host>:8090/api/stats?uuid=<your snare uuid>).

**Comment by santiago92** [comment]
Thank , I'm going to  try access log. Are you planning to report events to a dashboard?

**Comment by glaslos** [comment]
There are no plans for a dashboard in the near future.
