### ISSUE TITLE
Rename --interface to --host-ip

### ISSUE THREAD

**Issue by glaslos** [mushorg/snare#35]
Optionally support --interface by retrieving the associated ip address and using that with aiohttp.

**Comment by glaslos** [comment]
Fixed with #37

**Comment by olivia-oj** [comment]
There's no mention of this change or the --host-ip argument in the Snare documentation (http://snare.readthedocs.io/en/latest/parameters.html). Future users of this service would likely be thankful to have this argument easily visible.
