### ISSUE TITLE
Snare is not cloning JPG, CSS files of website

### ISSUE THREAD

**Issue by hamza005** [mushorg/snare#40]
I'm trying to clone my [website](https://cms.comsats.edu.pk) but the snare is not cloning images, css etc.  I need some help...

![screenshot from 2016-12-09 19-23-45](https://cloud.githubusercontent.com/assets/20417498/21052133/2d75d3f2-be45-11e6-8998-652c9703e1ff.png)

**Comment by glaslos** [comment]
I think the regex here is too strict to capture your image tags: https://github.com/mushorg/snare/blob/master/clone.py#L70

**Comment by afeena** [comment]
Thanks for the issue.

I will try to make cloning a bit better this weekend :)

@glaslos Thanks for the hint :)

**Comment by afeena** [comment]
#41

**Comment by glaslos** [comment]
@hamza005 can you check with the new cloner from @afeena ? We just merged #41 which should help with your problem.

**Comment by hamza005** [comment]
thanks for the co-operation.
