### ISSUE TITLE
MIME-type guess

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#43]
We'd like to return content type not only based on filename, but also based on content

https://github.com/mushorg/tanner/issues/96#issuecomment-267042253

**Comment by hamza005** [comment]
Hope You will fix the problem soon :)

**Comment by afeena** [comment]
@hamza005 
As hot-fix, you can add these two lines before L228 https://github.com/mushorg/snare/blob/master/snare.py#L228:

```python
if '.aspx' in path:
    content_type = 'text/html'
```

**Comment by hamza005** [comment]
:) It worked . Thanks a lot for prompt response :)

**Comment by glaslos** [comment]
@hamza005 we merged changes #46 that should fix that. Please try with the latest version from github.
