### ISSUE TITLE
Attack Logs

### ISSUE THREAD

**Issue by hamza005** [mushorg/snare#44]
I have successfully cloned my website with SNARE. Tanner is also installed and in working form. Question is where do i can find the attack logs generated by SNARE and Tanner?

**Comment by afeena** [comment]
By default, logs are stored in /opt/tanner/tanner.log

**Comment by hamza005** [comment]
Yes you are right but those are only application logs not the logs where the user name and passwords are being saved or logged. I want to track those logs. Can you please help me find them?

**Comment by afeena** [comment]
I'm not sure that I understand you right, but you can see some info about session via TANNER API
``<your_tanner_host>:8090/api/stats?uuid=<SNARE UUID>``

(your uuid store in /opt/snare/snare.pid file)
or directly get it from redis (snare uuid is a key)

**Comment by hamza005** [comment]
Actually the site i have cloned is my institutes's student portal. So i want to know that who is accessing this site. Like other honey pots generate logs of attacker's source IP address as well as password and user names they tried to get access.

**Comment by afeena** [comment]
TANNER has the docs. Please, read it.

**Comment by hamza005** [comment]
Okay, thanks for being so cooperative.

**Comment by glaslos** [comment]
I assume he want the payload of the request.

**Comment by hamza005** [comment]
exactly sir...!!! Sorry to bother both of you but i think this is the thing i need.

**Comment by afeena** [comment]
I understand, I think it might help https://github.com/mushorg/tanner/pull/95

**Comment by hamza005** [comment]
Hi there, I have read the Tanner docs for session. Now let me explain my issue. Have you ever use the honey pot like cowrie? Surely Yes. there is a file in cowrie honey pot named "cowrie.log" that stores all the session info of the a session including source and destination's IP, ports, time, Password/user name used. So my question is that which file in Tanner stores such session logs for tanner?

**Comment by afeena** [comment]
Session class doesn't store user/password records.
Did you see my previous message with pr?

**Comment by afeena** [comment]
@hamza005 Has the problem been solved?

**Comment by Waseem-farooqui** [comment]
@afeena If I am using Mush's Tanner then how could I get the logs.
Specifically attack logs ?
