### ISSUE TITLE
Deprecated Low-level Server

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#55]
We use Low-Level Server, which has been deprecated since aiohttp version 1.2. It needs to be rewritten asap.

http://aiohttp.readthedocs.io/en/stable/server.html

**Comment by afeena** [comment]
aiohttp 2.0 was released yesterday (20.03), low-level server was deprecated.

**Comment by glaslos** [comment]
@afeena what is the priority of this issue?

**Comment by afeena** [comment]
@glaslos New server is already implemented in the develop branch, after testing we will release it.

**Comment by afeena** [comment]
done in v0.3
