### ISSUE TITLE
execution errors on windows 10 install

### ISSUE THREAD

**Issue by basd925** [mushorg/snare#63]
Built this on Windows 10 and then ran the suggested quick start commands.  I may not have configured the compile environment correctly, although "pip3 install -r requirements.txt" completes without error.  

Error in clone.py reported as "AttributeError: module 'os' has no attribute 'getuid'".  Error in snare.py reported as: "ModuleNotFoundError: No module named 'grp'".  (2nd error may be the result of the first, though?) See below:

E:\Git\data\snare>python clone.py --target http://example.com
Traceback (most recent call last):
  File "clone.py", line 167, in <module>
    main()
  File "clone.py", line 151, in main
    if os.getuid() != 0:
AttributeError: module 'os' has no attribute 'getuid'

E:\Git\data\snare>python snare.py --port 8080 --page-dir example.com
Traceback (most recent call last):
  File "snare.py", line 20, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'

**Comment by afeena** [comment]
Hi @basd925. 
1. `os.getuid()` function available only in Unix https://docs.python.org/3/library/os.html#os.getuid
2. `grp` module provides access to the Unix group database. https://docs.python.org/3/library/grp.html

Thanks for the issue!

**Comment by basd925** [comment]
Thanks.

I suspected this, I think I had a similar problem with os.getuid() when I was working with packages
from a different project that was cross-platform.  I normally work in Linux, but since Windows is
apparently a giant security risk waiting to happen, I thought it would be good to get this running
on my Win10 machine.  I'm going to try a Linux install as well.

I will try commenting out the appropriate lines in my Windows copy of the git repository if I can
find them and see if that gets the system up and running.  Another alternative is to add a routine
to check and see if the machine is Windows-based (or alternatively if it is [not] Linux-based). 
Such as verify os.getuid() is not empty, I imagine.

**Comment by glaslos** [comment]
See #65

**Comment by exeptionerror** [comment]
[[Solved] ModuleNotFoundError: No module named ‘grp’ on windows
](https://exerror.com/modulenotfounderror-no-module-named-grp-on-windows/)
