### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by eliuha** [mushorg/snare#66]
When trying to access to not existing page, snare shows generic 404 error, which is replaces by chrome to standard error message 

`This 127.0.0.2 page can’t be found
No webpage was found for the web address: http://127.0.0.2:8080/aaa/wp-content/aaa
Search Google for 127 8080 aaa content
HTTP ERROR 404
`

wouldn't it make sense to redirect to the index page or show a custom error?

**Comment by afeena** [comment]
Hi @elihua, thanks for the issue :) It will be good feature for the snare :) I think we could try to fetch error page style from the original site while cloning

**Comment by rnehra01** [comment]
Also, when we access a path like `/some_path?foo=bar` and if no attack is present in `foo` param then snare return 404(assume some_path exists). Usually, most websites return `/some_path` if we pass arbitrary GET params to it. So we can include that too.

**Comment by glaslos** [comment]
Solved by #93
