### ISSUE TITLE
All requests throw errors.

### ISSUE THREAD

**Issue by seccentral** [mushorg/snare#67]
Howdy, 
I'm havin trouble gettin snare to work, all requests to any cloned page end up throwing errors. 
Here's a log  https://pastebin.com/twdntc0d
Debian 9 64bits, 
python 3.5.3 
fresh dev virtual machine, followed instructions by the letter. 
cloned duckduckgo.com : page displays without styling and images. and snare throws those errors  in the log i posted.

**Comment by afeena** [comment]
Hi @seccentral 
Did you use local tanner? Or default? As I see from logs, tanner response causes the error
