### ISSUE TITLE
Snare not working

### ISSUE THREAD

**Issue by rnehra01** [mushorg/snare#71]
If I start Snare without tanner then it throws 500 to all requests.

**Comment by rnehra01** [comment]
The reason is [this](https://github.com/mushorg/snare/blob/master/snare.py#L191) line. Since TANNER is not running, so `event_result` will be None and trying to access NoneType as a dict produces erro

**Comment by afeena** [comment]
Check for None must be added :)
Btw, which branch have you used? Without tanner - it means you used default tanner or you passed local tanner when it was off?

**Comment by rnehra01** [comment]
Sorry, didn't understand what you mean by `default tanner`. I started SNARE like `sudo python3 snare.py --page-dir example.com`, so there is no Tanner service.

**Comment by afeena** [comment]
If you run snare like this, you use default tanner https://github.com/mushorg/snare/blob/master/snare.py#L419

**Comment by rnehra01** [comment]
So, I guess I can deploy a `fix` for cases when SNARE can't successfully post to TANNER and `event_result` get set to `None`.

**Comment by afeena** [comment]
Yes, sure :)

**Comment by rnehra01** [comment]
I think #67 is same.
