### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by viskey98** [mushorg/snare#94]
After the new release there is a new argument --max-depth for clone.py  and it takes default argument of a huge value (sys.maxsize). A person who is new to snare will try to clone without this argument (as per the current version of README.md) , which will lead to cloning forever . So we can add this argument in our README.md.

**Comment by mzfr** [comment]
@viskey98 what do you mean by "cloning forever" ?

**Comment by viskey98** [comment]
@mzfr Try cloning without the --max-depth argument , it will try to clone all the web-pages (into its full depth) present in that website.
For instance take github.com , our cloner will try to clone all of the repositories present in github with full depth, which means it won't stop and runs 'forever'
